### ISSUE TITLE
how to exclude directory add in phar. such as logs and temp

### ISSUE THREAD

**Issue by nroe** [MacFJA/PharBuilder#22]
```
PHP Fatal error:  Uncaught exception 'Zend_Log_Exception' with message '"phar:///path/bin/main.phar/logs/run.log" cannot be opened with mode "a"' in phar:///path/bin/main.phar/vendor/zf1/zend-log/library/Zend/Log/Writer/Stream.php:81
Stack trace:
#0 phar:///path/bin/main.phar/configs/core.php(52): Zend_Log_Writer_Stream->__construct('phar:///path/b...')
#1 phar:///path/bin/main.phar/bin/cli.php(14): require_once('phar:///path/b...')
#2 /path/bin/main.phar(2): include('phar:///path/b...')
#3 {main}
  thrown in phar:///path/bin/main.phar/vendor/zf1/zend-log/library/Zend/Log/Writer/Stream.php on line 81

Fatal error: Uncaught exception 'Zend_Log_Exception' with message '"phar:///path/bin/main.phar/logs/run.log" cannot be opened with mode "a"' in phar:///path/bin/main.phar/vendor/zf1/zend-log/library/Zend/Log/Writer/Stream.php:81
Stack trace:
#0 phar:///path/bin/main.phar/configs/core.php(52): Zend_Log_Writer_Stream->__construct('phar:///path/b...')
#1 phar:///path/bin/main.phar/bin/cli.php(14): require_once('phar:///path/b...')
#2 /path/bin/main.phar(2): include('phar:///path/b...')
#3 {main}
  thrown in phar:///path/bin/main.phar/vendor/zf1/zend-log/library/Zend/Log/Writer/Stream.php on line 81
```

**Comment by kelunik** [comment]
You're probably using `__DIR__`. You have to use the path of the phar instead: `Phar::running(true)`.

**Comment by MacFJA** [comment]
I thinks that the error is thrown because you try to open in write mode a file in the Phar archive.
But Phar archives are read only (in most of case).

What you can do is: write your log outsite your phar(application), or have a different behavior if you are in a Phar archive.

**Comment by MacFJA** [comment]
@nroe, do you still have the issue?
